### ISSUE TITLE
バイナリファイルの削除

### ISSUE THREAD

**Issue by Code-Hex** [programing4/programing4#8]
`server` があるから消して再コミット！
他の issue も忘れずに！

![](http://wisard-hp.com/blog/wp-content/uploads/%E6%80%92%E3%82%8A%EF%BC%81%EF%BC%81.jpg)

**Comment by kazuminn** [comment]
消したぜ！

こんな感じに蹴散らしたぜ！

<pre>
$ git rm server
</pre>

**Comment by Code-Hex** [comment]
いい話！
